---
title: "Evaluating Average Grocery Discounts by Store and Month in Canada in 2024"
author: 
  - Fangning Zhang
  - Cher Ning-Li
  - Kevin Roe
thanks: "Code and data are available at: [https://github.com/Kanghyunroe/grocery_discount](https://github.com/Kanghyunroe/grocery_discount)."
date: today
date-format: long
abstract: "In a period of high grocery prices, grocery price discounts have helped lower costs of living for Canadians. The paper evaluates average grocery discounts by store and month and found that the highest discounts occured in September and at Walmart *insert number*. This is because there are a lot more back-to-school sales and Walmart is known to have generous discounts. The results of the paper informs shoppers' spending patterns to find the best deal."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```

# Introduction

Since the end of the pandemic with rising inflation, grocery prices have been a contentious topic of concern for Canadians. While grocery chains have raised prices, they also have introduced various discounts to encourage shopping. 

[insert results and scope of the study]

Understanding the results of the paper suggests when what month and grocery chains has the highest average discount for each month, allowing us to make better shopping decisions. 

The paper is structured as follows: @sec-data focuses on the data and measurement methods; @sec-results focuses on the results; @sec-discussion evaluates correlation vs causation, missing data and different sources of bias. 



# Data {#sec-data}

The dataset was obtained from @citeData, and contains pricing information about products offered across 8 major grocers across Canada — Voila, T&T, Loblaws, No Frills, Metro, Galleria, Walmart and Save-On-Foods. The pricing data was compiled from the vendor's websites directly. One table, named Product, contained information about the product name and vendor. Another table, named Raw, tracked all the price changes of these products, including the original price, new price, and time of price change each time it occurred. The time frame that the data covers is from February 28, 2024 until November 14, 2024 around noon. 

Using SQL, the data was cleaned and organized to locate patterns. This dataset contained many entries where data was incorrectly entered, often with the word "was" under the variable tracking original price. There are also events that are not price changes, such as out of stock notices, that are recorded in Raw. These events are distinguished by a null value in the old_price column. Both of these occurences were filtered out using SQL. To find patterns, the average discount amount for each month and each vendor was also calculated using SQL.

We used the statistical programming language `R` [@citeR] to produce graphs to better visualize the data cleaned by SQL. 

# Results {#sec-results}




# Discussion {#sec-discussion}

September highest discount

Walmart and Galleria in September

If we split each vendor have highest highest vendor - likely because of back2skool sales 

## Correlation vs Causation {#sec-discussion-correlation-and-causation}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Missing Data {#sec-discussion-missing-data}

The dataset only records data from February 28th, 2024 to November 11th, 2024. The problem is then that the February entry in *iNSERT FIGURE* does not accurately reflect the average grocery discount. For future study, I'd want to have a greater variation of our data across multiple years so we can find a more accurate the average grocery discount for each month. 

Moreover, the database had a lot of errors where either discounts were not listed, not all the entries were discounts, and the discount values were listed in text. All three errors made certain values unusable, leading us to filter them out of the dataset. 

## Sources of Bias {#sec-discussion-bias} 

\newpage

\appendix

# Appendix {-}

\newpage


# References


